"""create initial models

Revision ID: bd346dfafe92
Revises:
Create Date: 2026-10-01 20:32:53.885595

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bd346dfafe92"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "TRAVELER",
                "GUIDE",
                name="userrole",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("city", sa.String(length=80), nullable=True),
        sa.Column("bio", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("role IN ('TRAVELER', 'GUIDE')", name="userrole"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "slots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guide_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("start_at", sa.DateTime(), nullable=False),
        sa.Column("end_at", sa.DateTime(), nullable=False),
        sa.Column(
            "price_inr", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("(true)"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["guide_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("slots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_slots_guide_id_start_at", ["guide_id", "start_at"], unique=False
        )

    op.create_table(
        "bookings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slot_id", sa.Integer(), nullable=False),
        sa.Column("traveler_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CONFIRMED",
                "CANCELLED",
                name="bookingstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING', 'CONFIRMED', 'CANCELLED')", name="bookingstatus"
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"],
            ["slots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["traveler_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bookings", schema=None) as batch_op:
        batch_op.create_index(
            "uq_bookings_active_slot_traveler",
            ["slot_id", "traveler_id"],
            unique=True,
            sqlite_where=sa.text("status IN ('PENDING', 'CONFIRMED')"),
            postgresql_where=sa.text("status IN ('PENDING', 'CONFIRMED')"),
        )
        batch_op.create_index(
            "uq_bookings_confirmed_slot",
            ["slot_id"],
            unique=True,
            sqlite_where=sa.text("status = 'CONFIRMED'"),
            postgresql_where=sa.text("status = 'CONFIRMED'"),
        )

    op.create_table(
        "booking_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("booking_id", sa.Integer(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "PENDING",
                "CONFIRMED",
                "CANCELLED",
                name="bookingstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "PENDING",
                "CONFIRMED",
                "CANCELLED",
                name="bookingstatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("reason", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "from_status IN ('PENDING', 'CONFIRMED', 'CANCELLED')", name="bookingstatus"
        ),
        sa.CheckConstraint(
            "to_status IN ('PENDING', 'CONFIRMED', 'CANCELLED')", name="bookingstatus"
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["booking_id"],
            ["bookings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("booking_events")
    with op.batch_alter_table("bookings", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_bookings_confirmed_slot",
            sqlite_where=sa.text("status = 'CONFIRMED'"),
            postgresql_where=sa.text("status = 'CONFIRMED'"),
        )
        batch_op.drop_index(
            "uq_bookings_active_slot_traveler",
            sqlite_where=sa.text("status IN ('PENDING', 'CONFIRMED')"),
            postgresql_where=sa.text("status IN ('PENDING', 'CONFIRMED')"),
        )

    op.drop_table("bookings")
    with op.batch_alter_table("slots", schema=None) as batch_op:
        batch_op.drop_index("ix_slots_guide_id_start_at")

    op.drop_table("slots")
    op.drop_table("users")
    # ### end Alembic commands ###
